name: Keep Alive

on:
  schedule:
    - cron: '*/14 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping app
        run: curl -s https://intelligent-task-manager-7hrh.onrender.com/docs
